---
name: ci
on:
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup CUE
        uses: cue-lang/setup-cue@v1.0.1
      - name: Install jq
        uses: dcarbone/install-jq-action@v2
      - name: 👹 FINAL COSTS 👹
        run: |
          echo
          cue eval --out json | jq -r 'to_entries | map(select(.key != "schema" and .value.finalCost and .value.pricePerHour) | "\(.key): \(.value.currency)\(.value.finalCost)") | .[]'
